name: Explore Linux Environment - Lab 2
on: [push]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Grant Execute Permissions
        run: chmod +x ./build-gate.sh
        
      - name: Execute Build Gate Script
        run: build-gate.sh