name: Explore the Linux Environment
on: [push]
jobs:
  build: 
    runs-on: ubuntu-latest
    steps: 
      - name: Explore
        run: |
          echo "Current user running this script: $(whoami)"
          echo "Current directory path: $(pwd)"
          
          # List all environment variables, search for 'GITHUB' using grep
          env | grep GITHUB
          
          # Redirect an error stream to a log file
          cat non_existent_file.txt 2> error.log || true
          cat error.log
